### ISSUE TITLE
I don't want custom outcomes

### ISSUE THREAD

**Issue by k2helix** [I2000C/NewAmazingLuckyBlocks#13]
Hi, I just started using this plugin and I have noticed that custom outcomes drop rate is higher than normal outcomes rate, so I removed all custom outcomes but now the plugin doesn't load and gives the following error:

````
java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.FileConfiguration.getConfigurationSection(String)" is null
	at i2000c.newalb.custom_outcomes.utils.OutcomeManager.loadOutcomes(OutcomeManager.java:49) ~[?:?]
	at i2000c.newalb.NewAmazingLuckyBlocks.onEnable(NewAmazingLuckyBlocks.java:170) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:511) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:425) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:619) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:266) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1010) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:305) ~[server.jar:3217-Spigot-b166a49-4f6bcc8]
	at java.lang.Thread.run(Thread.java:831) [?:?]
````

I think that this should not happen so I'm asking for a fix. Thanks in advance.

**Comment by I2000C** [comment]
Delete the "custom_outcomes.yml" file, reload the plugin (reloading the server or using /alb reload), to regenerate the file.
Then, open the file and change the 'Main-probability' from 100 to 0.

In future releases, that value will be 0 by default.

**Comment by k2helix** [comment]
Thanks for the answer! I did it and now it works as I was requesting. Congrats for the awesome plugin!

**Comment by I2000C** [comment]
Thank you and if you like the plugin don't forget to review it in spigot. :).

P.S.: Custom outcomes can be very interesting. If you want to edit them or create yours, use "/alb menu"
