### ISSUE TITLE
NullPointerException while loading a schematic

### ISSUE THREAD

**Issue by tomestorm38** [I2000C/NewAmazingLuckyBlocks#18]
When the plugin should load a schematic while opening a luckyblock, the schematic won't come and I get this erro message:
 [NewAmazingLuckyBlocks] An error occurred while executing structure reward platt.schem:
[12:22:25] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Constructor.newInstance(Object[])" because "me.i2000c.newalb.utils2.Schematic.bukkitWorldConstructor" is null
[12:22:25] [Server thread/WARN]: 	at NewAmazingLuckyBlocks (2).jar//me.i2000c.newalb.utils2.Schematic.pasteAt(Schematic.java:211)
[12:22:25] [Server thread/WARN]: 	at NewAmazingLuckyBlocks (2).jar//me.i2000c.newalb.custom_outcomes.utils.rewards.StructureReward.execute(StructureReward.java:128)
[12:22:25] [Server thread/WARN]: 	at NewAmazingLuckyBlocks (2).jar//me.i2000c.newalb.custom_outcomes.utils.Outcome.lambda$execute$1(Outcome.java:245)
[12:22:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[12:22:25] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[12:22:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1490)
[12:22:25] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[12:22:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1414)
[12:22:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1187)
[12:22:25] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:302)
[12:22:25] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833
[log.txt](https://github.com/I2000C/NewAmazingLuckyBlocks/files/9308006/log.txt)
)

**Comment by I2000C** [comment]
Maybe the WorldEdit library has been updated, so I will have to update it in the plugin.
I will try to fix it as soon as possible.

**Comment by I2000C** [comment]
I have just fixed it, I will upload a release soon.
